"""
ne.data
    Functions for processing and splitting data
"""

import numpy
from enum        import Enum
from collections import namedtuple

# Helper tuples for representing feature selectors
FeatureSelector = namedtuple('FeatureSelector', ['name', 'n_features'])
Pearsons = lambda n: FeatureSelector('pearsons', n)
PCA      = lambda n: FeatureSelector('pca',      n)

# Helpers tuples for splitting data
Pair  = namedtuple(typename='Pair',  field_names=['xs', 'ys'])
Split = namedtuple(typename='Split', field_names=['train', 'test', 'val'])


class Dataset:


    def __init__(self, name, loader, labels):
        self._name   = name
        self._loader = loader
        self._labels = labels
        self._loaded = {}

    def data(self, selector=None, ratio=(0.8, 0.1, 0.1)):
        data = self._ensure_loaded(selector)
        xs   = data[:, :-1]
        ys   = data[:,  -1]
        return self._make_split(xs, ys, ratio)        

    def _ensure_loaded(self, selector):
        from os.path import exists

        if selector in self._loaded:
            # Already in cache
            pass

        elif exists(self._filename(selector)):
            # Available via file
            self._loaded[selector] = numpy.load(self._filename(selector))

        elif selector is None:
            # Unprocessed data is generated by evaluting loader()
            numpy.random.seed(2019_2020)
            data = numpy.asarray(list(self._loader()))
            p    = numpy.random.permutation(data.shape[0])
            self._loaded[selector] = data[p]
            numpy.save(self._filename(selector), self._loaded[selector])
            
        else:
            # Processed data required the unprocessed data first
            data = self._loaded[None]
            if type(selector) == Pearsons:
                raise NotImplementedError('Pearsons')
            elif type(selector) == PCA:
                raise NotImplementedError('PCA')
            else:
                # Unknown type
                raise Exception('Unknown feature selector {}'.format(type(selector)))
            # self._loaded[selector] = processed data
        
        return self._loaded[selector]
        
    def _filename(self, selector):
        from os.path import join

        if selector is None:
            # Unprocessed data is in ne/data/name/data.npy
            d = ['data.npy']
        else:
            # Processed data is in ne/data/name/selector/data_n.npy
            d = [ selector.name, 'data_{}.npy'.format(selector.n_features) ]
        return join('ne', 'data', self._name, *d)

    def _make_split(self, xs, ys, ratio):
        assert 0.0 <= sum(ratio)
        assert sum(ratio) <= 1.0
        a = round(xs.shape[0] * ratio[0])
        b = round(xs.shape[0] * ratio[1]) + a
        c = round(xs.shape[0] * ratio[2]) + b
        return Split(train=Pair(xs=xs[ :a], ys=ys[ :a]),
                     test =Pair(xs=xs[a:b], ys=ys[a:b]),
                     val  =Pair(xs=xs[b:c], ys=ys[b:c]))
